name: Rust CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: [ clippy, rustfmt ]
    - name: Clippy
      uses: actions-rs/clippy@master
      with:
        args: --manifest-path athena/Cargo.toml --all-features --all-targets
    - name: rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path athena/Cargo.toml -- --check
  test-metis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path metis/Cargo.toml --all-features
  test-athena:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path athena/Cargo.toml --release --all-features
