name: Rust CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Clippy
      run: |
        cd athena
        cargo clippy --all-features --all-targets
    - name: rustfmt
      run: |
        cd metis
        cargo fmt -- --check
        cd ../athena
        cargo fmt -- --check
  test-metis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Test
      run: |
        cd metis
        cargo test --all-features
  test-athena:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: |
        cd athena
        cargo build --release --all-features
