name: Rust CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Clippy
      run: cargo --color always clippy --manifest-path athena/Cargo.toml --all-features --all-targets -- -D warnings
    - name: rustfmt
      run: |
        cargo --color always fmt --manifest-path metis/Cargo.toml -- --check
        cargo --color always fmt --manifest-path athena/Cargo.toml -- --check
  test-metis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Test
      run: cargo --color always test --manifest-path metis/Cargo.toml --all-features
  test-athena:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Build
      run: cargo --color always build --manifest-path athena/Cargo.toml --release --all-features
